config/routes.rb
Rails.application.routes.draw do
  devise_for :owners
  root to: 'home#index'
  get 'home/about'
  get 'home/help'
  post '/', to: 'home#index'
  get 'home/search_book'
  post 'home/search_book', to: 'home#search_book'
  get 'home/search_borrower'
  post 'home/search_borrower', to: 'home#search_borrower'
  resources :books
  #post 'borrowers/lend/:id/', to: 'borrowers#borrow', as: 'borrower_borrow'
  resources :borrowers do
    member do
      get :lend
      post :lend
      post :return_book
    end
  end
  #get 'borrowers/:id/lend/', to: 'borrowers#lend'
  #post 'borrowers/lend/:id', to: 'borrowers#lend'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #match '*path', to: 'application#error404', via: :all
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :owner

  has_many :book_borrowers
  has_many :borrowers, through: :book_borrowers, dependent: :destroy

  validates :ISBN, presence: true
  validates :name, presence: true
  validates :author, presence: true
  validates :publisher, presence: true

  def self.search(search)
    return nil unless search
    Book.where("name LIKE ?", "%#{search}%")
  end
end

app/models/book_borrower.rb
class BookBorrower < ApplicationRecord
  belongs_to :book
  belongs_to :borrower

end

app/models/borrower.rb
class Borrower < ApplicationRecord
  has_many :book_borrowers
  has_many :books, through: :book_borrowers, dependent: :destroy

  validates :name, presence: true
  validates :twitter_id, presence: true

  def self.search(search)
    return nil unless search
    Borrower.where("name LIKE ?", "%#{search}%")
  end
end

app/models/owner.rb
class Owner < ApplicationRecord
  has_many :books, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_host
  #rescue_from ActiveRecord::RecordNotFound, ActionController::RoutingError, with: :error404
  #rescue_from Exception, with: :error500

  def set_host
    Rails.application.routes.default_url_options[:host] = request.host_with_port
  end

  def error404
    render 'error/error404', status: 404, formats: [:html]
  end

  def error500
    render 'error/error500', status: 500, formats: [:html]
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :redirect_login
  def show
    @book = current_owner.books.find(params[:id])
    @borrower = @book.borrowers.last
  end
  def new
    @book = current_owner.books.build
  end
  def create
    @book = current_owner.books.build(book_params)
    if @book.save
      redirect_to root_path, notice: "作成しました。"
    else
      flash[:notice] = "入力ミスがあります。"
      render :new
    end
  end

  def destroy
    @book = current_owner.books.find(params[:id])
    @book.destroy
    redirect_to root_path, notice: "削除しました。"
  end

  def edit
    @book = current_owner.books.find(params[:id])
  end
  def update
    @book = current_owner.books.find(params[:id])
    if @book.update(book_params)
      redirect_to @book, notice: "更新しました。"
    else
      flash[:notice] = "入力ミスがあります。"
      render :edit
    end
  end

  def redirect_login
    unless owner_signed_in?
      redirect_to new_owner_session_path
    end
  end

  private

  def book_params
    params.require(:book).permit(
      :ISBN, :name, :author, :publisher
    )
  end

end

app/controllers/borrowers_controller.rb
class BorrowersController < ApplicationController
  before_action :redirect_login

  def show
    @borrower = Borrower.find(params[:id])
    @books = @borrower.books
    @active_books = @books.distinct
  end

  def new
    @borrower = Borrower.new
  end

  def create
    @borrower = Borrower.new(borrower_params)
    if @borrower.save
      flash[:notice] = "登録しました"
      redirect_to @borrower, notice: "登録しました。"
    else
      flash[:notice] = "入力ミスがあります。"
      render :new
    end
  end

  def edit
    @borrower = Borrower.find(params[:id])
  end

  def update
    @borrower = Borrower.find(params[:id])
    if @borrower.update(borrower_params)
      redirect_to @borrower, notice: "更新しました。"
    else
      flash[:notice] = "入力ミスがあります。"
      render :edit
    end
  end

  def lend
    @search_books = Book.where(owner_id: current_owner.id).search(params[:search])
    @borrower = Borrower.find(params[:id])
    if request.post?
      @book_borrower = BookBorrower.new(:book_id =>params[:book_id], :borrower_id=>@borrower.id)
      if @book_borrower.save
        @book = Book.find(params[:book_id])
        @book.activate = true
        @book.save
        flash[:alert] = Book.find(params[:book_id]).activate
        flash[:notice] = "貸し出しました。"
        redirect_to @borrower
      end
    end
  end

  def return_book
    @borrower = Borrower.find(params[:id])
    if request.post?
      @book = Book.find(params[:book_id])
      @book.activate = false
      @book.save
      #flash[:notice] = Book.find(params[:book_id]).activate
      redirect_to @borrower
    end
  end

  def destroy
    @borrower = Borrower.find(params[:id])
    @borrower.destroy
    redirect_to root_path, notice: "削除しました。"
  end

  def redirect_login
    unless owner_signed_in?
      redirect_to new_owner_session_path
    end
  end

  private
  def borrower_params
    params.require(:borrower).permit(
      :name, :twitter_id
    )
  end
  def book_borrower_params
    params.require(:book_borrower).permit(
      :borrower_id, :book_id
    )
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :redirect_login, except: [:about, :help]

  def index
      @books = current_owner.books.paginate(page: params[:page], per_page: 8)
      @search_books = Book.where(owner_id: current_owner.id).search(params[:search])
  end

  def about
  end

  def help
  end

  def search_book
    @search_books = Book.where(owner_id: current_owner.id).search(params[:search])
  end

  def search_borrower
    @search_borrowers = Borrower.search(params[:search])
  end

  def redirect_login
    unless owner_signed_in?
      redirect_to new_owner_session_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/borrowers_helper.rb
module BorrowersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/books/edit.html.erb
<% if owner_signed_in? %>
  <br/>
  <div id="to_white">
    <h5>本の編集</h5><br/>
    <%= form_for(@book) do |f| %>
      <div class="field">
        <i class="material-icons">format_list_numbered</i>
        <label>ISBN</label><br/>
        <%= f.text_field :ISBN, placeholder: "Please type book ISBN." %>
      </div>
      <div class="field">
        <i class="material-icons">book</i>
        <label>書籍名</label><br/>
        <%= f.text_field :name, placeholder: "Please type book name." %>
      </div>
      <div class="field">
        <i class="material-icons">people</i>
        <label>著者</label><br/>
        <%= f.text_field :author, placeholder: "Please type book author." %>
      </div>
      <div class="field">
        <i class="material-icons">location_city</i>
        <label>出版社</label><br/>
        <%= f.text_field :publisher, placeholder: "please type book publisher" %>
      </div>
      <br/>
      <%= f.submit "Update", class: "btn" %>
    <% end %>
  </div>
<% else %>
<% end %>

app/views/books/new.html.erb
<% if owner_signed_in? %>
  <br/>
  <div id="to_white">
    <h5>本の新規登録</h5><br/>
    <%= form_for(@book) do |f| %>
      <div class="field">
        <i class="material-icons">format_list_numbered</i>
        <label>ISBN</label><br/>
        <%= f.text_field :ISBN, placeholder: "Please type book ISBN." %>
      </div>
      <div class="field">
        <i class="material-icons">book</i>
        <label>書籍名</label><br/>
        <%= f.text_field :name, placeholder: "Please type book name." %>
      </div>
      <div class="field">
        <i class="material-icons">people</i>
        <label>著者</label><br/>
        <%= f.text_field :author, placeholder: "Please type book author." %>
      </div>
      <div class="field">
        <i class="material-icons">location_city</i>
        <label>出版社</label><br/>
        <%= f.text_field :publisher, placeholder: "please type book publisher" %>
      </div>
      <br/>
      <%= f.submit "登録", class: "btn" %>
    <% end %>
  </div>

<% else %>
<% end %>

app/views/books/show.html.erb
<% if owner_signed_in? %>
  <br/>
  <div id="to_white">
    <h5>詳細</h5><br/>
    <table class="collection">
      <tr class="collection-item">
        <th><i class="material-icons">format_list_numbered</i><label>ISBN</label></th>
        <td><%= @book.ISBN %></td>
      </tr>
      <tr class="collection-item">
        <th><i class="material-icons">book</i><label>書籍名</label></th>
        <td><%= @book.name %></td>
      </tr>
      <tr class="collection-item">
        <th><i class="material-icons">people</i><label>著者</label></th>
        <td><%= @book.author %></td>
      </tr>
      <tr class="collection-item">
        <th><i class="material-icons">location_city</i><label>出版社</label></th>
        <td><%= @book.publisher %></td>
      </tr>
      <tr class="collection">
        <th></th><td></td>
      </tr>
    </table>
    <label>貸し出し状況</label>
    <% if @book.activate and !@borrower.nil? %>
      <div class="collection">
        <%= link_to(@borrower, class: "collection-item") do %>
          <%= @borrower.name %>
        <% end %>
      </div>
    <% else %>
      <h6>貸し出せます。</h6>
    <% end %><br/>
    <%= link_to "Edit this book", edit_book_path, class: "btn" %>
    <%= link_to "delete this book", @book, class: "btn red", method: :delete,
                data: { confirm: "You sure?" }%>
  </div>
<% else %>
<% end %>

app/views/borrowers/edit.html.erb
<% if owner_signed_in? %>
  <br/>
  <div id="to_white">
    <h5>貸出先の編集</h5><br/>
    <%= form_for(@borrower) do |f| %>
      <div class="field">
        <i class="material-icons">person</i>
        <label>名前</label><br/>
        <%= f.text_field :name, placeholder: "borrower name." %>
      </div>
      <div class="field">
        <i class="material-icons">account_circle</i>
        <label>Twitter ID</label><br/>
        <%= f.text_field :twitter_id, placeholder: "twitter_id" %>
      </div>
      <%= f.submit "Update", class: "btn" %>
    <% end %>
  </div>
<% else %>
<% end %>

app/views/borrowers/lend.html.erb
<% if owner_signed_in? %>
  <div id="to_white">
    <h5>本の貸し出し</h5>
    <%= @borrower.name %>さんの貸し出し画面です。
    <%= form_tag(url: lend_borrower_path(@borrower), class: "field", method: "get") do %>
      <br/>
      <label class="material-icons">search</label>
      <%= text_field_tag(:search, '', placeholder: "本の名前を入力してください。") %>
      <%= submit_tag("検索", class: "btn", url: @borrower) %>
    <% end %><br/>
    <% if @search_books.nil? %>
      <h6>当てはまる書籍はありません。</h6>
    <% else %>
      <% @search_books.each do |book| %>
        <div class="collection">
          <div class="collection-item">
            <%= book.name %>
          </div>
          <% if book.activate %>
            <%= link_to "貸し出し不可", "#", class: "btn red" %>
          <% else %>
            <%= link_to "貸し出し可", lend_borrower_path(:book_id=>book.id),
                        class: "btn blue", :method => :post,
                        data: { confirm: "貸し出しますか？" } %>
          <% end %>
        </div>
      <% end %>
    <% end %>
  </div>
<% else %>
<% end %>

app/views/borrowers/new.html.erb
<% if owner_signed_in? %>
  <br/>
  <div id="to_white">
    <h5>貸出先の新規登録</h5><br/>
    <%= form_for(@borrower, url: {action: "create"}) do |f| %>
      <div class="field">
        <i class="material-icons">person</i>
        <label>名前</label>
        <%= f.text_field :name, placeholder: "borrower name." %>
      </div>
      <div class="field">
        <i class="material-icons">account_circle</i>
        <label>Twitter ID</label><br/>
        <%= f.text_field :twitter_id, placeholder: "borrower twitter_id" %>
      </div>
      <%= f.submit "登録", class: "btn" %>
      <br/>
    <% end %>
  </div>
<% else %>

<% end %>

app/views/borrowers/show.html.erb
<% if owner_signed_in? %>
  <br/>
  <div id="to_white">
    <h5>詳細</h5><br/>
    <table class="collection">
      <tr class="collection-item">
        <th><i class="material-icons">format_list_numbered</i><label>名前</label></th>
        <td><%= @borrower.name %></td>
      </tr>
      <tr class="collection-item">
        <th><i class="material-icons">book</i><label>Twitter ID</label></th>
        <td><%= @borrower.twitter_id %></td>
      </tr>
      <tr class="collection">
        <th></th><td></td>
      </tr>
    </table>
    <label>貸し出し中</label><br/>
    <div class="collection">
      <% @active_books.each do |book| %>
        <% if book.borrowers.last == @borrower and book.activate %>
          <%= link_to(book, class: "collection-item") do %>
            <%= book.name %>
          <% end %>
          <%= link_to "返却", return_book_borrower_path(:book_id=>book.id),
                      class: "btn", :method => :post,
                      data: { confirm: "返却しますか？" } %>
          <div class="divider"></div>
        <% end %>
      <% end %>
    </div><br/>
    <label>貸し出し履歴</label><br/>
    <div class="collection">
      <% @books.each do |book| %>
        <%= link_to(book, class: "collection-item") do %>
          <%= book.name %>
          <%= book.created_at %>
        <% end %>
      <% end %>
    </div><br/>
    <%= link_to 'Lend this borrower', lend_borrower_path, class: "btn" %>
    <%= link_to "Edit this borrower", edit_borrower_path, class: "btn" %><br/><br/>
    <%= link_to "delete this borrower", @borrower, class: "btn red", method: :delete,
                data: { confirm: "You sure?" }%>
  </div>
<% else %>
<% end %>

app/views/home/about.html.erb
<br/>
<div class="support_page">
  <h1>Home#about</h1>
  <p>Find me in app/views/home/about.html.erb</p>
</div>

app/views/home/help.html.erb
<br/>
<div class="support_page">
  <h1>Home#help</h1>
  <p>Find me in app/views/home/help.html.erb</p>
</div>

app/views/home/index.html.erb
<div class="main">
  <h5>蔵書一覧</h5><br/>
  <div class="collection">
    <% @books.each do |book| %>
      <%= link_to(book) do %>
        <%= link_to(book, class: "collection-item") do %>
          <%= book.name %>
        <% end %>
      <% end %>
    <% end %>
  </div>
  <br/>
  <%= will_paginate @books %>
  <%= link_to "＋", new_book_path, class: "btn-floating btn-large waves-effect waves-light red right" %>
  <br/><br/><br/>
  <div class="search-books hide-on-med-and-down">
    <%= render 'parts/search_book' %>
  </div>
</div>

app/views/home/search_book.html.erb
<br/>
<div id="to_white">
  <%= form_tag(url: root_path, class: "field", method: "get") do %>
    <label class="material-icons">search</label>
    <%= text_field_tag(:search, '', placeholder: "本の名前を入力してください。") %>
    <%= submit_tag("検索", class: "btn") %>
  <% end %><br/>
  <% if @search_books.nil? %>
    <h6>当てはまる書籍はありません。</h6>
  <% else %>
    <div class="collection">
      <% @search_books.each do |book| %>
        <%= link_to(book, class: "collection-item") do %>
          <%= book.name %>
        <% end %>
      <% end %>
    </div>
  <% end %><br/>
  <%= link_to "＋", new_book_path, class: "btn-floating btn-large waves-effect waves-light red right" %><br/><br/>
</div>

app/views/home/search_borrower.html.erb
<br/>
<div id="to_white">
  <h5>貸出先の検索</h5>
  <%= form_tag(url: root_path, class: "field", method: "get") do %>
    <label class="material-icons">search</label>
    <%= text_field_tag(:search, '', placeholder: "貸出先の名前を入力してください。") %>
    <%= submit_tag("検索", class: "btn") %>
  <% end %><br/>
  <% if @search_borrowers.nil? %>
    <h6>当てはまる書籍はありません。</h6>
  <% else %>
    <div class="collection">
      <% @search_borrowers.each do |borrower| %>
        <%= link_to(borrower, class: "collection-item") do %>
          <%= borrower.name %>
        <% end %>
      <% end %>
    </div>
  <% end %>
  <br/>
  <%= link_to "＋", new_borrower_path, class: "btn-floating btn-large waves-effect waves-light red right" %><br/>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lender</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'parts/header' %>
    <%= render 'parts/flash' %>
    <%= render 'parts/side_nav' %>
    <div class="container">
      <div class=""><%= yield %></div>
    </div>
  </body>
</html>

app/views/parts/_flash.html.erb
<% unless flash.empty? %>
  <script>
      <% flash.each do |key, message| %>
        M.toast({html: '<%= message %>'})
      <% end %>
  </script>
<% end %>

app/views/parts/_header.html.erb
<nav>
  <div class="nav-wrapper container">
    <%= link_to image_tag("logo.png", class: "brand-logo left", size: '90x60'), root_path %>
    <ul id="nav-mobile" class="right hide-on-med-and-down">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "About", home_about_path %></li>
      <li><%= link_to "Help", home_help_path %></li>
    </ul>
    <ul id="dropdown-target" class="dropdown-content">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "About", home_about_path %></li>
      <li><%= link_to "Help", home_help_path %></li>
    </ul>
    <a  href="#" class="dropdown-trigger right hide-on-large-only" data-target="dropdown-target"><i class="material-icons">arrow_drop_down</i></a>
  </div>
</nav>
<script>
    $(".dropdown-trigger").dropdown();
</script>

app/views/parts/_search_book.html.erb
<%= form_tag(url: root_path, class: "field", method: "get") do %>
  <h5>蔵書の検索</h5>
  <label class="material-icons">search</label>
  <%= text_field_tag(:search, '', placeholder: "本の名前を入力してください。") %>
  <%= submit_tag("検索", class: "btn") %>
<% end %><br/>
<% if @search_books.nil? %>
  <h6>当てはまる書籍はありません。</h6>
<% else %>
  <div class="collection">
    <% @search_books.each do |book| %>
      <%= link_to(book, class: "collection-item") do %>
        <%= book.name %>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/parts/_side_nav.html.erb
<% if owner_signed_in? %>
  <ul id="slide-out" class="sidenav">
    <br/><br/><br/>
    <li><%= link_to 'アカウントの編集', edit_owner_registration_path %></li>
    <li><div class="divider"></div></li>
    <li><%= link_to '蔵書の検索', home_search_book_path %></li>
    <li><div class="divider"></div></li>
    <li><%= link_to '貸出先の検索', home_search_borrower_path %></li>
    <li><div class="divider"></div></li>
    <li><%= link_to '貸出先の新規登録', new_borrower_path %></li>
    <li><div class="divider"></div></li>
    <li><%= link_to 'ログアウト', destroy_owner_session_path, method: :delete %></li>
    <li><div class="divider"></div></li>
    <li><%= link_to "アカウント削除", registration_path(current_owner), data: { confirm: "本当によろしいですか?" }, method: :delete, class: "red-text text-darken-2" %></li>
  </ul>
  <a href="#" data-target="slide-out" class="sidenav-trigger"><i class="material-icons large-size menu position">menu</i></a>
<% end %>

<script>
  $('.sidenav').sidenav();
</script>